In [14]:
egg_count = 12

def buy_eggs(egg_count=3):
    egg_count += 12
    print(egg_count)

# print(buy_eggs(egg_count))
print(buy_eggs(egg_count))

24
None


In [16]:
str1 = 'Functions are important programming concepts.'

def print_fn():
    str1 = 'Variable scope is an important concept.'
    print(str1)
    
print_fn()

Variable scope is an important concept.


In [21]:
import assignment1

string = "Intro to Python"

print(assignment1.count_uppercase(string))

2


In [22]:
######################### NUMPY #########################

In [2]:
!pip3 install numpy

In [3]:
import numpy

In [15]:
## Array
numpy.__version__
array1 = numpy.array([
    [1,2,3],
    [4,5,6],
    [10,11,12],
])
print(array1)
print(array1[0])
print(array1[2,1])
print(array1[2][1])

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
[1 2 3]
11
11


In [18]:
list1 = [
    [1,2,3],
    [4,5,6],
    [10,11,12],
]
print(list1)
print(list1[2],[1])

[[1, 2, 3], [4, 5, 6], [10, 11, 12]]
[10, 11, 12] [1]


In [21]:
array1.dtype

dtype('int64')

In [24]:
# shape of array
print('shape of array1:', array1.shape)
print('dimension of array1:', array1.ndim)

shape of array1: (3, 3)
dimension of array1: 2


In [25]:
array3 = numpy.array([
    [
        [1,2,3],
        [11,22,33],
    ],
    [
        [4,5,6],
        [44,55,66],
    ]
])

In [27]:
print('shape of array3:', array3.shape)
print('dimension of array3:', array3.ndim)

shape of array3: (2, 2, 3)
dimension of array3: 3


In [37]:
array_zeros_1 = numpy.zeros(10)
array_zeros_2 = numpy.zeros((10,5))
array_zeros_3 = numpy.zeros((5,10,10))

print(array_zeros_1,array_zeros_1.shape)
print("-----------------")
print(array_zeros_2,array_zeros_2.shape)
print("-----------------")
print(array_zeros_3,array_zeros_3.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,)
-----------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] (10, 5)
-----------------
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0

In [39]:
array_ones_1 = numpy.ones(10)
array_ones_2 = numpy.ones((10,5))
array_ones_3 = numpy.ones((5,10,10))

print(array_ones_1,array_ones_1.shape)
print("-----------------")
print(array_ones_2,array_ones_2.shape)
print("-----------------")
print(array_ones_3,array_ones_3.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] (10,)
-----------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] (10, 5)
-----------------
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1

In [41]:
array_empty_1 = numpy.empty(10)
array_empty_2 = numpy.empty((10,5))
array_empty_3 = numpy.empty((5,10,10))

print(array_empty_1,array_empty_1.shape)
print("-----------------")
print(array_empty_2,array_empty_2.shape)
print("-----------------")
print(array_empty_3,array_empty_3.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] (10,)
-----------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] (10, 5)
-----------------
[[[6.91260370e-310 6.91260370e-310 2.47097644e-316 2.47097644e-316
   4.57890143e-072 0.00000000e+000 4.66376555e-033 7.25416361e-043
   4.08221323e-033 1.79339649e-052]
  [3.12075289e-033 7.25416369e-043 4.08221323e-033 1.79339649e-052
   2.40554560e-057 3.43569187e+179 1.57670235e-052 3.11276487e+179
   2.90887861e-033 3.92576963e+179]
  [1.57670234e-052 3.11276487e+179 6.01334523e-154 7.27485464e-043
   1.43258180e-153 1.58794297e-047 1.05840524e+141 5.93053436e-038
   5.20844069e-090 3.21493397e-057]
  [5.20555299e-090 9.49765700e-043 5.20364279e-090 6.37257830e-067
   5.20938823e-090 1.95994460e-062 8.24024461e-067 4.58777536e-072
   4.76192700e-038 1.96900462e-062]
  [8.24024461e-067 1.29134396e-057 2.73826582e-057 2.4422

In [48]:
array_arrange = numpy.arange(0,22,2)
print(array_arrange)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [53]:
array_append = numpy.array([0,1,2])
numpy.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
array_reshape = numpy.arange(12).reshape((3, 4))
print(array_reshape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
array_logic = numpy.array([1, 5, 7, 8, 16, 21, 23, 33, 36, 41, 48, 49, 51, 56, 58, 64, 70, 75, 92, 99])